services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      SETTLY_DB_PASSWORD: ${SETTLY_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "127.0.0.1:5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "127.0.0.1:9090:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: