spring:
  application:
    name: settly-api
  profiles:
    active: dev

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:                                                                                                                                                                                                                                                               
            jwk-set-uri: http://localhost/auth/realms/settly/protocol/openid-connect/certs

keycloak:
  client-id: settly
  admin:
    server-url: http://localhost/auth
    realm: settly
    client-id: settly-api-admin

gemini:
  api:
    key: ${GEMINI_API_KEY}
